FROM nvcr.io/nvidia/deepstream:7.1-samples-multiarch

RUN apt-get update && \
    apt-get install -y software-properties-common \
    libgstrtspserver-1.0-0 gir1.2-gst-rtsp-server-1.0 \
    gstreamer1.0-libav \  
    python3-venv python3-dev libgirepository1.0-dev libcairo2-dev

RUN apt install --reinstall -y gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libavutil56 libavcodec58 libavformat58 libavfilter7 libx264-155 libde265-dev libde265-0 libx265-179 libvpx6 libmpeg2encpp-2.1-0 libmpeg2-4 libmpg123-0; exit 0

ARG ENVDIR=/opt/venv/
RUN mkdir -p ${ENVDIR} && python3 -m venv ${ENVDIR}
ENV PATH=${ENVDIR}/bin:$PATH
RUN chmod -R 777 ${ENVDIR}/

RUN pip install --upgrade pip setuptools
RUN pip3 install cupy-cuda12x==13.4.1 Cython cuda-python==12.9.0 numpy==1.26.4 \ 
    opencv-python==4.10.0.84 \
    pygobject==3.50.0 \
    pycairo==1.27.0

RUN pip3 install https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.2.0/pyds-1.2.0-cp310-cp310-linux_aarch64.whl

RUN apt-key adv --fetch-key https://repo.download.nvidia.com/jetson/jetson-ota-public.asc && \
    add-apt-repository 'deb https://repo.download.nvidia.com/jetson/common r36.4 main' && \
    apt-get update && apt-get install -y python3.10-vpi3 && \
    ln -s /opt/nvidia/vpi3/lib64/python/vpi.cpython-310-aarch64-linux-gnu.so ${ENVDIR}/lib/python3.10/site-packages/
